extends: airbnb
parserOptions: 
  ecmaVersion: 6
rules:
  no-underscore-dangle: 0
env:
  node: true
  es6: true
  mocha: true
globals:
  request: true
  assert: true
  expect: true
  joiAssert: true
  getCollection: true