extends: airbnb
parserOptions: 
  ecmaVersion: 6
rules:
  no-underscore-dangle: "off"
  no-unused-expressions: 
    - "error" 
    - allowShortCircuit: true
env:
  node: true
  es6: true
  mocha: true
globals:
  request: true
  sinon: true
  expect: true
  joiAssert: true
  getCollection: true