verbose: false
instrumentation:
  include-all-sources: true
reporting:
  print: both
check:
  global:
    statements: 80
    lines: 80
    branches: 69 #algo está errado, o valor não bate com o sumário
    functions: 80
    excludes: []
  each:
    statements: 0
    lines: 0
    branches: 0
    functions: 0
    excludes: []